package org.projectsw.View;

public enum UIEvent {
    TILE_SELECTION, CONFIRM_SELECTION, COLUMN_SELECTION, TILE_INSERTION, SAY_IN_CHAT, CHOOSE_NICKNAME, CHOOSE_NICKNAME_AND_PLAYER_NUMBER, CHECK_EXISTS_FIRST_PLAYER
}
