package org.projectsw.Exceptions;

public enum ErrorName {
    NO_ERROR,
    EMPTY_TEMPORARY_POINTS,
    INVALID_RECIPIENT,
    LOBBY_CLOSED,
    MAXIMUM_PLAYERS,
    MINIMUM_REDEEMED_POINTS,
    NO_MORE_COLUMN_SPACE,
    UNSELECTABLE_COLUMN,
    UNSELECTABLE_TILE,
    UPDATING_ON_WRONG_PLAYER,
    INVALID_TEMPORARY_TILE

}
