package org.projectsw.Exceptions;

public enum ErrorName {
    NULL,
    EMPTY_TEMPORARY_POINTS,
    INVALID_NAME,
    INVALID_NUMBER_OF_PLAYERS,
    LOBBY_CLOSED,
    MAXIMUM_PLAYERS,
    MINIMUM_REDEEMED_POINTS,
    NO_MORE_COLUMN_SPACE,
    UNSELECTABLE_COLUMN,
    UNSELECTABLE_TILE,
    UPDATING_ON_WRONG_PLAYER

}
