package org.projectsw.Model.Enums;

public class DataForGame {

    private String[][][] personals = {
            {
                    {
                            "PLANTS",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "CATS"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "BOOKS",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "GAMES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "PLANTS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "CATS",
                            "EMPTY",
                            "GAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "BOOKS"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "FRAMES"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "FRAMES",
                            "EMPTY",
                            "EMPTY",
                            "GAMES",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "PLANTS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "CATS",
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "BOOKS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "GAMES"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "TROPHIES",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "PLANTS",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "BOOKS",
                            "CATS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "FRAMES",
                            "BOOKS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "PLANTS"
                    },
                    {
                            "GAMES",
                            "EMPTY",
                            "EMPTY",
                            "CATS",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY",
                            "CATS"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "BOOKS",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "GAMES",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY"
                    },
                    {
                            "PLANTS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "CATS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "PLANTS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "TROPHIES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "GAMES"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "BOOKS",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "FRAMES"
                    },
                    {
                            "EMPTY",
                            "CATS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "PLANTS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "BOOKS",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "GAMES",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "GAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "CATS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "BOOKS"
                    },
                    {
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY",
                            "EMPTY",
                            "PLANTS"
                    },
                    {
                            "FRAMES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES"
                    },
                    {
                            "EMPTY",
                            "GAMES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "BOOKS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "CATS",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "FRAMES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "PLANTS",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "PLANTS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "BOOKS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "GAMES",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "CATS"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY"
                    }
            },
            {
                    {
                            "EMPTY",
                            "EMPTY",
                            "BOOKS",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "PLANTS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "FRAMES",
                            "EMPTY",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "TROPHIES",
                            "EMPTY"
                    },
                    {
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "GAMES"
                    },
                    {
                            "CATS",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY",
                            "EMPTY"
                    }
            }
    };

    private String[][][] boards = {
            {
                    {"UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED"},
                    {"UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED"},
                    {"UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED"}
            },
            {
                    {"UNUSED","UNUSED","UNUSED","EMPTY","UNUSED","UNUSED","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY"},
                    {"UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED"},
                    {"EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","UNUSED","UNUSED","EMPTY","UNUSED","UNUSED","UNUSED"}
            },
            {
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY"},
                    {"EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY"},
                    {"EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED"},
                    {"UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"},
                    {"UNUSED","UNUSED","UNUSED","UNUSED","EMPTY","EMPTY","UNUSED","UNUSED","UNUSED"}
            }
    };

    public String[][][] getBoards() {
        return this.boards;
    }

    public String[][][] getPersonals() {
        return this.personals;
    }
}
