package org.projectsw.Model.Enums;

public enum GameEvent{
    UPDATED_BOARD,
    UPDATED_SHELF,
    UPDATED_TEMPORARY_TILES,
    UPDATED_CURRENT_PLAYER,
    UPDATED_CHAT,
    ERROR,
    NEXT_PLAYER_TURN_NOTIFY,
    SELECTION_NOT_POSSIBLE,
    EMPTY_TEMPORARY_TILES,
    PERSONAL_GOAL,
}
